### ISSUE TITLE
transfer the competition to the new Codlab site

### ISSUE THREAD

**Issue by phoenixsecularbird** [awslabs/fever#9]
Hello! The old Codlab site has stopped service, and I cannot submit my results any more. Will you transfer the competition to the new Codlab site? Thank you!

**Comment by christos-c** [comment]
Hi @phoenixsecularbird, thanks for pointing this out. We have now re-created the competition on the new Codalab site: https://codalab.lisn.upsaclay.fr/competitions/7308 although we haven't tested it extensively. Feel free to make a submission and if you find any issues please report back to us.

**Comment by phoenixsecularbird** [comment]
&nbsp; OK! Thanks a lot! I have succeeded to submit on the new site!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "awslabs/fever"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月12日(星期一) 晚上9:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [awslabs/fever] transfer the competition to the new Codlab site (Issue #9)





 
Hi @phoenixsecularbird, thanks for pointing this out. We have now re-created the competition on the new Codalab site: https://codalab.lisn.upsaclay.fr/competitions/7308 although we haven't tested it extensively. Feel free to make a submission and if you find any issues please report back to us.

**Comment by christos-c** [comment]
Great, thanks for confirming! I'll resolve this issue.
